Inquiry list view added
aayushKhandpur/creativei_inquiry pull request #24
Opened 2018-02-06 13:10 UTC by keshavgr8

Finishes story [#154697533](https://www.pivotaltracker.com/story/show/154697533)
![inq-list-viewpr](https://user-images.githubusercontent.com/20260001/35861292-36c1d76e-0b6d-11e8-8856-c1803ac872f2.jpg)

2018-02-06 19:00 UTC, aayushKhandpur commented on client-src/src/pages/inq-list/inq-list.html
> +              <ion-icon name="flash" style="color:#ffd633"></ion-icon>
Can we avoid inline css?

2018-02-06 19:02 UTC, aayushKhandpur requested changes
Address review

2018-02-06 19:24 UTC, keshavgr8 commented on client-src/src/pages/inq-list/inq-list.html
> +              <ion-icon name="flash" style="color:#ffd633"></ion-icon>
fixed in commit e00635f

2018-02-07 06:41 UTC, aayushKhandpur requested changes
Resolve conflicts.

2018-02-08 06:16 UTC, keshavgr8 commented
Conflicts resolved

2018-02-08 06:42 UTC, aayushKhandpur approved these changes

2018-02-08 07:59 UTC, merged