Inquiry get request
aayushKhandpur/creativei_inquiry pull request #9
Opened 2018-01-20 20:13 UTC by jitendra20

Inquiry requests added except getByStatus

2018-01-21 07:04 UTC, aayushKhandpur requested changes
Resolve conflicts and resubmit PR

2018-01-21 08:03 UTC, jitendra20 commented
Issues Resolved in commit 47b61ff

2018-01-22 16:52 UTC, aayushKhandpur commented on src/main/java/creativei/helper/ResponseHelper.java
>         while (iterator.hasNext()) {
Any reason why you used iterator instead of forEach loop?

2018-01-22 16:56 UTC, aayushKhandpur approved these changes
1. Merge Request mapping pincode branch first.
2. Reverse merge master in "Inquiry get request" branch.
3. Merge this branch into master.

2018-01-22 17:25 UTC, merged